/* use petSalon; */
CREATE TABLE EMPLOYEE (
    SSN VARCHAR(15) PRIMARY KEY,
    Number VARCHAR(10),
    Street VARCHAR(50),
    Apartment_number VARCHAR(10),
    State VARCHAR(20),
    City VARCHAR(30),
    Zip VARCHAR(10),
    Salary INT,
    Month INT,
    Day INT,
    Year INT,
    First_name VARCHAR(30),
    Middle_name VARCHAR(30),
    Last_name VARCHAR(30),
    Phone_number VARCHAR(15),
    Email VARCHAR(50),
    Emergency_contact VARCHAR(15),
    Male BOOLEAN,
    Female BOOLEAN
);

CREATE TABLE SALON (
    Name VARCHAR(50),
    Address VARCHAR(100),
    PRIMARY KEY (Name)
);

CREATE TABLE CUSTOMER (
    ID INT PRIMARY KEY,
    First_name VARCHAR(30),
    Middle_name VARCHAR(30),
    Last_name VARCHAR(30),
    Number VARCHAR(10),
    Street VARCHAR(50),
    Apartment_number VARCHAR(10),
    State VARCHAR(20),
    City VARCHAR(30),
    Zip VARCHAR(10),
    Phone_number VARCHAR(15),
    Email VARCHAR(50),
    Emergency_contact VARCHAR(15),
    Salon_name VARCHAR(100),
    FOREIGN KEY (Salon_name) REFERENCES SALON(Name)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE TABLE PET (
    ID INT PRIMARY KEY,
    Name VARCHAR(30),
    DOB DATE,
    Age INT,
    CustomerID INT,
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE GROOMER (
    Name VARCHAR(100),
    SSN VARCHAR(15) PRIMARY KEY,
    FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE STAFF (
    Name VARCHAR(100),
    SSN VARCHAR(15),
    PRIMARY KEY (Name, SSN),
    FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE EMPLOYS (
    SSN VARCHAR(15),
    Name VARCHAR(100),
    PRIMARY KEY (SSN, Name),
    FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (Name) REFERENCES SALON(Name)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE HELPS (
    SSN VARCHAR(15),
    ID INT,
    PRIMARY KEY (SSN, ID),
    FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (ID) REFERENCES CUSTOMER(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE GROOMS (
    SSN VARCHAR(15),
    ID INT,
    PRIMARY KEY (SSN, ID),
    FOREIGN KEY (SSN) REFERENCES GROOMER(SSN)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (ID) REFERENCES PET(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE PET_MULTIVALUE (
    ID INT PRIMARY KEY,
    Breed_type VARCHAR(30),
    FOREIGN KEY (ID) REFERENCES PET(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

